# Generated by Django 3.2.4 on 2026-01-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_instance_id', models.CharField(max_length=255, unique=True)),
                ('operator', models.CharField(max_length=255)),
                ('search_path', models.TextField()),
                ('suffix', models.CharField(max_length=255)),
                ('backup_path', models.TextField()),
                ('bk_job_link', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('host_count', models.IntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BizInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(unique=True)),
                ('bk_biz_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_module_id', models.IntegerField(unique=True)),
                ('bk_module_name', models.CharField(max_length=100)),
                ('bk_set_id', models.IntegerField()),
                ('bk_biz_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_set_id', models.IntegerField(unique=True)),
                ('bk_set_name', models.CharField(max_length=100)),
                ('bk_biz_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_host_id', models.IntegerField()),
                ('file_path', models.TextField()),
                ('file_size', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='home_application.backupjob')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
