# Generated by Django 3.2.4 on 2026-01-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HelloWorld",
        ),
    ]
