# Generated by Django 3.2.4 on 2026-01-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_delete_helloworld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuprecord',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='backuprecord',
            name='file_size',
        ),
    ]
