# Generated by Django 3.2.4 on 2026-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20260106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='file_path',
            field=models.CharField(default='undefined', max_length=1024),
            preserve_default=False,
        ),
    ]
