# Generated by Django 3.2.4 on 2026-01-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0004_backuprecord_file_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="backuprecord",
            old_name="file_path",
            new_name="bk_backup_name",
        ),
    ]
