# Generated by Django 3.2.4 on 2026-01-06 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0005_rename_file_path_backuprecord_bk_backup_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="backuprecord",
            name="bk_file_create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
