# Generated by Django 3.2.4 on 2026-01-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0006_backuprecord_bk_file_create_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuprecord",
            name="bk_file_create_time",
        ),
    ]
