# Generated by Django 3.2.25 on 2026-01-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0010_apirequestcount_error_count"),
    ]

    operations = []
