# Generated by Django 3.2.25 on 2026-01-22 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0012_create_sync_api_counts_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestcount',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='统计日期'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='apirequestcount',
            unique_together={('api_category', 'api_name', 'date')},
        ),
    ]
