# Generated by Django 3.2.25 on 2026-01-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0014_auto_20260126_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('success', 'success'), ('failed', 'failed'), ('partial', 'partial')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='syncstatus',
            name='last_status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending'), ('running', 'running')], max_length=20, null=True),
        ),
    ]
