# Generated by Django 3.2.25 on 2026-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0015_auto_20260129_1757"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=128, unique=True, verbose_name="用户名")),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理员"), ("ops", "运维"), ("dev", "开发"), ("bot", "机器人")],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "用户角色",
                "verbose_name_plural": "用户角色",
            },
        ),
    ]
