# Generated by Django 3.2.25 on 2026-02-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0017_create_push_metrics_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "top_category",
                    models.CharField(
                        choices=[
                            ("permission_denied", "权限不足"),
                            ("disk_full", "磁盘空间不足"),
                            ("path_not_found", "路径不存在"),
                            ("network_error", "网络连接异常"),
                            ("timeout", "执行超时"),
                            ("agent_offline", "Agent离线"),
                            ("script_error", "脚本执行错误"),
                            ("unknown", "未知原因"),
                        ],
                        max_length=32,
                        verbose_name="主要失败类型",
                    ),
                ),
                ("summary", models.TextField(verbose_name="诊断摘要")),
                ("suggestion", models.TextField(verbose_name="修复建议")),
                ("detail", models.JSONField(default=dict, verbose_name="详细诊断数据")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backup_job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis",
                        to="home_application.backupjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能诊断记录",
                "verbose_name_plural": "智能诊断记录",
            },
        ),
    ]
