# Generated by Django 3.2.25 on 2026-03-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_application", "0018_diagnosisrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosisrecord",
            options={"verbose_name": "诊断记录", "verbose_name_plural": "诊断记录"},
        ),
        migrations.AlterField(
            model_name="diagnosisrecord",
            name="top_category",
            field=models.CharField(
                choices=[
                    ("permission_denied", "权限不足"),
                    ("disk_full", "磁盘空间不足"),
                    ("path_not_found", "路径不存在"),
                    ("network_error", "网络连接异常"),
                    ("timeout", "执行超时"),
                    ("agent_offline", "Agent离线"),
                    ("unknown", "未知原因"),
                ],
                max_length=32,
                verbose_name="主要失败类型",
            ),
        ),
    ]
